name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Migrate
      run: |
        cp psycity/psycity/settings.py.sample psycity/psycity/base_settings.py
        echo "from base_settings import *" > psycity/psycity/settings.py
        cat psycity/psycity/sqlite.py.sample >> psycity/psycity/settings.py
        cd psycity
        python manage.py makemigrations
        python manage.py migrate

    - name: Run Tests
      run: |
        cd psycity
        python manage.py test

